version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
    container_name: elasticsearch
    ports: ['9200:9200']
    networks:
      - elkstack
    volumes:
      - 'es_data:/usr/share/elasticsearch/data'

  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.0
    container_name: kibana
    ports: ['5601:5601']
    networks:
      - elkstack
    depends_on: ['elasticsearch']

networks:
  elkstack:
    driver: bridge

volumes:
  es_data:
    driver: local
